spring:
  datasource:
    url: jdbc:mysql://localhost:3306/role_base_system
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    enable: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
